# Configuration for models, particularly if using LLM judges
llm_judge:
  provider: "openai"  # Supported: 'openai', 'anthropic' (add more in llm_judge.py if needed)
  model_name: "gpt-3.5-turbo" 
  api_key_env: "OPENAI_API_KEY" 
  generation_params:
    temperature: 0.7
    max_tokens: 250 

    